apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ctse-product-service
  name: ctse-product-service
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: ctse-product-service
status:
  loadBalancer: {}
