apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ctse-search-service
  name: ctse-search-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: ctse-search-service
status:
  loadBalancer: {}