apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: transport-servic
  name: transport-servic
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: transport-servic
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: transport-servic
    spec:
      containers:
        - image: sm2irfan/ctse-transport-service:{{tag}}
          imagePullPolicy: Always
          name: ctse-transport-service
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          ports:
            - containerPort: 8090
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
