apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: transport-servic
  name: transport-servic
spec:
  type: NodePort
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: transport-servic
status:
  loadBalancer: {}
