apiVersion: v1
kind: Service
metadata:l
  labels:
    app: ctse-user-service
  name: ctse-user-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: ctse-user-service
status:
  loadBalancer: {}