name: Payment Service Docker Build Deploy
on:
  pull_request:
    branches: [ master ]
env:
  GKE_ZONE: us-central1-c
  GKE_CLUSTER: ctse-project-cluster
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run shell script
      run: echo commit hash is ${{ github.sha }}
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: |
        cd ./payment-service 
        mvn --batch-mode --update-snapshots package
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.PAYMENT_SERVICE_DOCKER_USERNAME }}
        password: ${{ secrets.PAYMENT_SERVICE_DOCKER_ACCESS_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./payment-service/Dockerfile
        push: true
        tags: ${{ secrets.PAYMENT_SERVICE_DOCKER_USERNAME }}/ctse-payment-service:${{ github.sha }}
    - name: Update config files in k8s
      run: sed -i.bak 's/{{tag}}/${{ github.sha }}/g' k8s/payment-service-deploy.yaml && rm k8s/*.bak
    - name: Setup Google Cloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      with:
        service_account_key: ${{ secrets.GKE_USER_PAYMENT_SERVICES_KEY }}
        project_id: ${{ secrets.GKE_USER_PAYMENT_SERVICES_PROJECTID }}
    - name: Deploy Docker Image in Google Kubernetes Engine Cluster
      run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
        kubectl apply -f ./k8s/payment-service-deploy.yaml