name: Transport Service Docker Build Deploy
on:
  pull_request:
    branches: [transport-service]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run shell script
        run: echo commit hash is ${{ github.sha }}
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Build with Maven
        run: |
          cd ./transport-service 
          mvn --batch-mode --update-snapshots package
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.TRANSPORT_SERVICE_DOCKER_USERNAME }}
          password: ${{ secrets.TRANSPORT_SERVICE_DOCKER_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./transport-service/Dockerfile
          push: true
          tags: ${{ secrets.PAYMENT_SERVICE_DOCKER_USERNAME }}/ctse-transport-service:${{ github.sha }}
