name: User Service Docker Build Deploy
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run shell script
      run: echo commit hash is ${{ github.sha }}
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.USER_SERVICE_DOCKER_USERNAME }}
        password: ${{ secrets.USER_SERVICE_DOCKER_ACCESS_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: user-service/Dockerfile
        push: true
        tags: ${{ secrets.USER_SERVICE_DOCKER_USERNAME }}/ctse-user-service:${{ github.sha }}